project:
  type: website

website:
  title: "shiny-r-prod"
  description: "Website for the posit::conf(2023) workshop 'Shiny in Production: Tools and Techniques'"
  repo-url: "https://github.com/posit-conf-2023/shiny-r-prod"
  repo-actions: [edit, issue]
  open-graph: true
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    #css: styles.css
    toc: true



